.TH emu-checkout 1 July 14, 2015 "version 0.2.0" "Emu Manual"
.SH NAME
emu\-checkout \- Restore source from snapshot
.SH SYNOPSIS
.B emu checkout
[<options>] <sink>:<snapshot>
.SH DESCRIPTION
Restores the contents of a snapshot to the source directory, setting a
new sink head.
.PP
It uses the same difference and transfer algorithm as emu push, except
with the sink and source swapped so that the difference between the
contents of the specified sink snapshot and source is written to the
source, restoring the state of the source to match that of the
snapshot.
.SH OPTIONS
.TP
\-d \-\-dry-run
Perform a trial run with no changes made.
.TP
\-f \-\-force
Force checkout the snapshot, ignoring any concurrency locks on the source
or sink.
.TP
\-v \-\-verbose
Increase verbosity.
.TP
\-\-version
Show version information and quit.
.TP
\-h \-\-help
Show this help and quit.
.SH EMU
Part of the
.B emu
(1)
suite
.SH AUTHOR
Chris Cummins <chrisc.101@gmail.com>
.SH SEE ALSO
.B emu
(1)
