dist: trusty
sudo: required

os:
  - linux

language: python

python:
  - "3.6"

before_install:
  - virtualenv -p python3.6 env
  - source env/bin/activate
  - python --version

install:
  - python --version
  - python setup.py install

script:
  - python --version
  - python setup.py test
  - ./scripts/run-tests.sh
