language: python
python:
  - "2.7"

install:
  # Coverage packages are on a binstar channel:
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  # Install support for coveralls.io:
  - pip install coveralls coverage
  - python setup.py install

script:
  - coverage run --source=emu setup.py test

after_success:
  # Create coverage report:
  - coveralls

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
