dist: trusty
sudo: required

os:
  - linux
#  - osx  # "Python builds are not available on OS X"

env:
  EMU_MANDIR=man

language: python

python:
  - "3.6"

before_install:
  - virtualenv -p python3.6 env
  - source env/bin/activate
  - python --version
  - pip install coveralls

install:
  - mkdir -pv $EMU_MANDIR
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python setup.py test
  - ./scripts/run-tests.sh
  - test ! -f test.log || cat test.log

after_success:
  - coveralls
