dist: trusty
sudo: required

os:
  - linux

language: python

python:
  - "3.6"

before_install:
  - virtualenv -p python3.6 env
  - sudo sh -c "source env/bin/activate ; python --version"

install:
  - sudo sh -c "source env/bin/activate ; python setup.py install"

script:
  - sudo sh -c "source env/bin/activate ; python setup.py test"
  - ./scripts/run-tests.sh
