dist: trusty
sudo: required

os:
  - linux
# TODO:  - osx

env:
  EMU_MANDIR=man

language: python

python:
  - "3.6"

before_install:
  - virtualenv -p python3.6 env
  - source env/bin/activate
  - python --version

install:
  - mkdir -pv $EMU_MANDIR
  - python setup.py install

script:
  - python setup.py test
  - ./scripts/run-tests.sh
  - cat test.log
