#!/bin/bash

set -ex
test_setup

version="$(emu --version)"

exec_dir=/usr/local/bin
exec="$(find $exec_dir -name 'emu*')"

# Ensure we have some executables to test
test -n "$exec" || exit 2

for bin in $exec; do
    e=$(basename $bin)

    # emu-command --version
    $e --version > $e.version
    assert_strings_match "$e.version" "$version"
    rm -f $e.version

    # emu command --version
    emu ${e:4} --version > $e.version
    assert_strings_match "$e.version" "$version"
    rm -f $e.version
done

test_teardown
