#!/bin/sh

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")

# print the help text
help ()
{
    man emu
}

help_command ()
{
    local command="$1"

    if [ -n "$command" ]
    then
        local exec=emu-$command
        command -v $exec >/dev/null 2>&1 || { command_not_found "$command"; }
        $exec help
        exit 0
    else
        help
        exit 0
    fi
}

# print the version number
version ()
{
    emu_echo "version $EMU_VERSION"
}

# First we parse local args.
case $1 in
    "--help")
        help
        exit 0
        ;;
    "--version")
        version
        exit 0
        ;;
esac

# get arguments
while getopts ":hv" OPT
do
    case $OPT in
        h)
            help
            exit 0
            ;;
        v)
            version
            exit 0
            ;;
        \?)
            emu_error "invalid option: -$OPTARG"
            exit $EXIT_INVALID_ARGS
            ;;
        :)
            emu_error "option -$OPTARG requires an argument"
            exit $EXIT_INVALID_ARGS
            ;;
    esac
done

# get command
command="$1"
shift

# parse commands
case $command in
    "" | "help")
        help_command $@
        exit 0
        ;;
    "version")
        version
        exit 0
        ;;
    *)
        # execute command
        exec=emu-$command
        command -v $exec >/dev/null 2>&1 || { command_not_found "$command"; }
        $exec $@
        exit $?
        ;;
esac
