#!/bin/sh

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")

VERSION="0.0.1"

# Print the help text.
help ()
{
    man emu
}

help_command ()
{
    if [[ $1 != "" ]]
    then
        EXEC=emu-$1
        command -v $EXEC >/dev/null 2>&1 || { exit_command_not_found "$1"; }
        $EXEC help
        exit 0
    else
        help
        exit 0
    fi
}

# Print the version number.
version ()
{
    emu_echo "version $VERSION"
}

print_emu ()
{
    cat << EOF | less
                                       /-/-=/-=
                                      //  ZX   \"
                                    / /XZXZX(o)  ---,
                                    / XZXZXZXZX _____\`\\
                                     /ZXZXZXZX
                                      / ;,ZXZ
                                      /  :ZX%\\
                                      /%  : X\\
                                      :/:  %:X:
                                      /%:%   %\\\\
                                       /:%:  %  \\
                                       /  :%  : \\
                                        /  :%  :%\\
                                        /%  %    \\
                                        /%:  %:  %\\
                                        //%    :  %\\
                   %%%%%%%%%%  %% %%   /  /     :   :
              %%%%%%%%       %%  %   %%%%           \\:
            %%%%%%                                 : \\
          %%%%                                    :%:\\
       % %                                       %  \\
      %                                         %% \\
    %                                  %%% %%%%%% \\
  %                                 %%%%%%%% %%%\\
 %                                %%  %%%%%% %\\
 %                         %%%%%%%%%%%%% %%%%\\\\
 %%%%/%%%%%%%%%%%%%%%%%%%%%%% %%%%%%% %%% %%\\
 /       %%%%%%%%%  % %% % %%% % %%%%% %%%\\
                (_____)%%(_____)%%%%%%\\
              ((_____) ((____)
                (___)    (___)
                 (__)     (__)
                  (__)     (__)
                   (__)     (__)
                    (__)     (__)
                     (  )     (  )
                     (  )     (  )
                    (    )   (    )
                  (__    |  (___  |
              ___(  /  \\  \\____ \\  |---
            <(____/      \\_____(>\\_____(>
EOF
}

# Get arguments.
while getopts :hv OPT
do
    case $OPT in
        h)
            help
            exit 0
            ;;
        v)
            version
            exit 0
            ;;
        \?)
            emu_error "invalid option: -$OPTARG"
            exit $EXIT_INVALID_ARGS
            ;;
        :)
            emu_error "option -$OPTARG requires an argument."
            exit $EXIT_INVALID_ARGS
            ;;
    esac
done

# Get command.
COMMAND="$1"
shift

# Parse commands.
case $COMMAND in
    "" | "help")
        help_command $@
        exit 0
        ;;
    "version")
        version
        exit 0
        ;;
    "emu")
        print_emu
        exit 0
        ;;
    *)
        # Execute command.
        EXEC=emu-$COMMAND
        command -v $EXEC >/dev/null 2>&1 || { exit_command_not_found "$COMMAND"; }
        $EXEC $@
        exit $?
        ;;
esac
