#!/bin/bash

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")

help () {
    man $EMU_ECHO_PREFIX
}

set -e

# Enable debugging if needed.
test -n "$EMU_DEBUG" && set -x

# Parse --help argument first.
for arg in $@; do
    case "$arg" in
        "--help" | "help")
            help
            exit 0
    esac
done
