#!/bin/bash

source /usr/local/lib/libemu
SCRIPT=$(basename $0)
SOURCE_DIR="$(pwd)"

help ()
{
    man emu-restore
}

main ()
{
    if [ "$1" = "help" ]
    then
        help
        exit 0
    fi

    pre_exec_hooks "$SOURCE_DIR"
    lock_dir "$SOURCE_DIR"

    IN=$(echo "$1" | tr ":" "\n")

    if [[ $(echo "$IN" | wc -l) -ne 2 ]]
    then
        if [[ $(ls "$SOURCE_DIR/.$PROG/sinks" | wc -l) -eq 1 ]]
        then
            SINK="$(ls $SOURCE_DIR/.$PROG/sinks)"
        else
            echo "$SCRIPT: invalid snapshot"
            exit_with_error "$SOURCE_DIR"
        fi
    fi

    if [ "$SINK" = "" ]
    then
        SINK=$(echo "$IN" | head -n1)
    fi

    SINK_DIR="$(cat $SOURCE_DIR/.$PROG/sinks/$SINK 2>/dev/null)"
    if [[ ! -d "$SINK_DIR" ]]
    then
        echo "$SCRIPT: sink '$SINK' does not exist" >&2
        exit_with_error "$SOURCE_DIR"
    fi

    lock_dir "$SINK_DIR"

    SNAPSHOT=$(echo "$IN" | tail -n1)
    if [ "$SNAPSHOT" = "HEAD" ]
    then
        SNAPSHOT="$(cat "$SINK_DIR/.$PROG/HEAD")"
    fi

    SNAPSHOT_DIR="$SINK_DIR/.$PROG/trees/$SNAPSHOT"
    if [[ ! -d "$SNAPSHOT_DIR" ]]
    then
        echo "$SCRIPT: snapshot '$SNAPSHOT' does not exist" >&2
        exit_with_error "$SOURCE_DIR"
    fi

    rsync \
        --delete \
        --archive \
        --human-readable \
        --exclude-from="$SOURCE_DIR/.$PROG/excludes" \
        "$SNAPSHOT_DIR/" "$SOURCE_DIR"
    if (( $? ))
    then
        echo "$SCRIPT: restore of '$SINK:$SNAPSHOT' failed" >&2
    fi

    echo "$SCRIPT: SOURCE at '$SINK:$SNAPSHOT'"

    unlock_dir "$SINK_DIR"
    unlock_dir "$SOURCE_DIR"
    post_exec_hooks "$SOURCE_DIR"
}
main $@
