#!/bin/bash

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")

help ()
{
    man emu-reset
}

main ()
{
    if [ "$1" = "help" ]
    then
        help
        exit 0
    fi

    emu restore $@
    get_source_dir_or_fail
    pre_exec_hooks

    IN=$(echo "$1" | tr ":" "\n")

    if [[ $(echo "$IN" | wc -l) -ne 2 ]]
    then
        if [[ $(ls "$SOURCE_DIR/.emu/sinks" | wc -l) -eq 1 ]]
        then
            SINK="$(ls $SOURCE_DIR/.emu/sinks)"
        else
            emu_error "invalid snapshot"
            emu_panic
            exit $EMU_EXIT_INCORRECT_COMMAND
        fi
    fi

    if [ "$SINK" = "" ]
    then
        SINK=$(echo "$IN" | head -n1)
    fi

    SINK_DIR="$(cat $SOURCE_DIR/.emu/sinks/$SINK 2>/dev/null)"
    if [[ ! -d "$SINK_DIR" ]]
    then
        emu_error "sink '$SINK' does not exist"
        emu_panic
        exit $EMU_EXIT_ERROR
    fi

    SNAPSHOT=$(echo "$IN" | tail -n1)
    if [ "$SNAPSHOT" = "HEAD" ]
    then
        SNAPSHOT="$(cat "$SINK_DIR/.emu/HEAD")"
    fi

    SNAPSHOT_DIR="$SINK_DIR/.emu/trees/$SNAPSHOT"
    if [[ ! -d "$SNAPSHOT_DIR" ]]
    then
        emu_error "snapshot '$SNAPSHOT' does not exist"
        emu_panic
        exit $EMU_EXIT_ERROR
    fi

    post_exec_hooks "$SOURCE_DIR"

}
main $@
