#!/bin/bash

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")
SOURCE_DIR="$(pwd)"

main ()
{
    test -n "$EMU_DEBUG" && set -x
    exit_on_help_version $@

    get_source_dir_or_fail
    execute_hooks "pre" "$SOURCE_DIR"

    IN=$(echo "$1" | tr ":" "\n")

    if [[ $(echo "$IN" | wc -l) -ne 2 ]]
    then
        if [[ $(ls "$SOURCE_DIR/$EMU_DIR/sinks" | wc -l) -eq 1 ]]
        then
            # If there's only 1 sink, use that.
            SINK="$(ls $SOURCE_DIR/$EMU_DIR/sinks)"
        else
            emu_error "invalid snapshot"
            emu_panic
            exit $EMU_EXIT_INCORRECT_COMMAND
        fi
    fi

    if [ -z "$SINK" ]
    then
        SINK=$(echo "$IN" | head -n1)
    fi

    SINK_DIR="$(cat $SOURCE_DIR/$EMU_DIR/sinks/$SINK 2>/dev/null)"
    if [[ ! -d "$SINK_DIR" ]]
    then
        emu_error "sink '$SINK' does not exist"
        emu_panic
        exit $EMU_EXIT_INCORRECT_COMMAND
    fi

    SNAPSHOT=$(echo "$IN" | tail -n1)
    SNAPSHOT_DIR="$SINK_DIR/$EMU_DIR/trees/$SNAPSHOT"
    if [[ ! -d "$SNAPSHOT_DIR" ]]
    then
        emu_error "snapshot '$SNAPSHOT' does not exist"
        emu_panic
        exit $EMU_EXIT_INCORRECT_COMMAND
    fi

    $(verify_node "$SNAPSHOT_DIR")
    emu_echo "pass"

    execute_hooks "post" "$SOURCE_DIR"
    exit 0
}
main $@
