#!/bin/sh

SCRIPT=$(basename $0)
PROG="emu"

help ()
{
    echo "\
$SCRIPT - manage $PROG sinks.

With no arguments, show a list of existing sinks. Several subommands are
available to perform operations on sinks.

add <name> <path>
    Adds a sink name <name> for the directory at <path>.
rename <old> <new>
    Rename the sink named <old> to <new>.
rm <name>
    Remove the sink named <name>. Does not remove any $PROG files.
show <name>
    Gives some information about the sink <name>.
"
}

init_sink ()
{
    SINK_DIR="$1"

    mkdir -p "$SINK_DIR/.$PROG"
    mkdir -p "$SINK_DIR/.$PROG/trees"
    touch "$SINK_DIR/.$PROG/HEAD"
    echo $(pwd) > "$SINK_DIR/.$PROG/SOURCE"

    echo "$SCRIPT: Initialized sink at $SINK_DIR/.$PROG"
}

add_sink ()
{
    if [[ "$1" == "" ]] || [[ "$2" == "" ]]
    then
        help
        exit 1
    fi

    if [[ -f ".$PROG/sinks/$1" ]]
    then
        echo "$SCRIPT: Sink '$1' already exists." >&2
        exit 1
    fi

    if [[ -d "$2/.$PROG" ]]
    then
        echo "$SCRIPT: '$2/.$PROG' already exists." >&2
        exit 1
    fi

    # Create sinks/remote file.
    echo "$2" > ".$PROG/sinks/$1"

    # Initialize sink.
    init_sink "$2"
}

rm_sink ()
{
    if [[ ! -f ".$PROG/sinks/$1" ]]
    then
        echo "$SCRIPT: Sink '$1' does not exist." >&2
        exit 1
    fi

    rm -f ".$PROG/sinks/$1"
    echo "$SCRIPT: Sink '$1' removed."
}

show_sink ()
{
    if [[ ! -f ".$PROG/sinks/$1" ]]
    then
        echo "$SCRIPT: Sink '$1' does not exist." >&2
        exit 1
    fi

# TODO:
#   number of snapshots
#   last write time
#   directory size
    echo "\
* sink $1
  Path: $(cat .$PROG/sinks/$1)"
}

list_sinks ()
{
    ls ".$PROG/sinks"
}

COMMAND="$1"
shift

case "$COMMAND" in
    "help")
        help
        ;;
    "")
        list_sinks
        ;;
    "add")
        add_sink $1 $2
        ;;
    "rm")
        rm_sink $@
        ;;
    "show")
        show_sink $1
        ;;
esac

exit 0
