#!/bin/bash

source /usr/local/lib/libemu
EMU_ECHO_PREFIX=$(basename "$0")

main ()
{
    test -n "$EMU_DEBUG" && set -x
    exit_on_help_version $@

    get_source_dir_or_fail
    execute_hooks "pre" "$SOURCE_DIR"

    local input=$(echo "$1" | tr ":" "\n")

    if [[ $(echo "$input" | wc -l) -ne 2 ]]
    then
        if [[ $(ls "$SOURCE_DIR/$EMU_DIR/sinks" | wc -l) -eq 1 ]]
        then
            # If there's only 1 sink, use that.
            local sink="$(ls $SOURCE_DIR/$EMU_DIR/sinks)"
        else
            emu_error "invalid snapshot"
            emu_panic
            exit $EMU_EXIT_INCORRECT_COMMAND
        fi
    fi

    if [ -z "$sink" ]
    then
        local sink=$(echo "$input" | head -n1)
    fi

    local sink_dir="$(cat $SOURCE_DIR/$EMU_DIR/sinks/$sink 2>/dev/null)"
    if [[ ! -d "$sink_dir" ]]
    then
        emu_error "sink '$sink' does not exist"
        emu_panic
        exit $EMU_EXIT_INCORRECT_COMMAND
    fi

    local snapshot=$(echo "$input" | tail -n1)
    local node="$sink_dir/$EMU_DIR/trees/$snapshot"
    if [[ ! -d "$node" ]]
    then
        emu_error "snapshot '$snapshot' does not exist"
        emu_panic
        exit $EMU_EXIT_INCORRECT_COMMAND
    fi

    set -e
    verify_node "$node"
    set +e
    emu_echo "pass"

    exit 0
}
main $@
